### ISSUE TITLE
housekeeping genes for GRCm39

### ISSUE THREAD

**Issue by guillaumecharbonnier** [guillaumecharbonnier/mw-lib#19]
@SebastienNin 
I have just seen your comment
https://github.com/guillaumecharbonnier/mw-lib/blob/4bd595f72715a816f7ac9e527c67182236f3f310/src/snakemake/tables/bed_ids.tsv#L58

It is really low priority, but one solution would be to get the gene names from GRCm38 housekeeping genes and create a new equivalent bed file from GRCm39 gtf.

**Comment by SebastienNin** [comment]
Yeah for now it is a low priority, but I'll keep it in mind. I think I'll add it if we change the mouse reference genome in routine analysis.

**Comment by guillaumecharbonnier** [comment]
See you in 2022, or 2023... ;)
