### ISSUE TITLE
cellranger error

### ISSUE THREAD

**Issue by SebastienNin** [guillaumecharbonnier/mw-lib#22]
Hi @guillaumecharbonnier,
After pulling the master branch, I get an error when running cellranger mkfastq. 
Here is the error in the log.

`Failed` to parse the options: unrecognised option '--localcores'

I removed this option from my current branch and it works

I see that this option works for running on local mode. How can we do to make it work for you and for me?

Sebastien

**Comment by guillaumecharbonnier** [comment]
Oh I guess this option got deprecated, yes you can remove it. I am not using cellranger for now and I'll catch up only with your latest version.
Feel free to fix the master when something is not working in the scRNA and the fix is unlikely to affect non-single-cell rules.

**Comment by SebastienNin** [comment]
Okay, I removed it in commit [367b25e](https://github.com/guillaumecharbonnier/mw-lib/commit/367b25eb0c29965342280488462b5e4be2a36b0b)
